### ISSUE TITLE
useDeleteMutation doesn't allow multiple subsequent calls?

### ISSUE THREAD

**Issue by timohuisinga** [psteinroe/supabase-cache-helpers#348] opened 2023-12-09 11:28 UTC
As stated in the title it seems that calling useDeleteMutation multiple times subsequently is not possible.

I tried calling it within a forEach() loop and whenever the array contained more than one element i got the error: "The result contains 0 rows" for any element that is not the first one, even though all elements are definitely within the database. 
I am not quite sure if the term "hook" is applicable to these mutation functions. However, i am calling them like that for now, so i hope the description of my issue is understandable.

This is my implementation with the described behavior:
The hook:
```ts
export function useDeleteAnswersExercise() {
  return handleErrors(
    useDeleteMutation(
      supabase.from("answers_exercises"),
      ["exercise", "order_position"],
      "exercise,order_position",
    ),
  );
}
```
importing the hook:
```ts
const { trigger: deleteAnswersExercise } = useDeleteAnswersExercise();
```
triggering the hook: 
```ts
async function deleteAnswers(
    initial: [string, boolean, number][],
    answers: [string, boolean, number][],
  ) {
    initial
      .filter((e, index) => {
        return answers[index] === undefined;
      })
      .forEach((e) => {
        deleteAnswersExercise({ exercise: listItem.id, order_position: e[2] });
      });
  }
```
also for testing purposes i tried triggering the hook two times by just hardcoding the table entries to delete:
```ts
deleteAnswersExercise({ exercise: listItem.id, order_position: 5 });
deleteAnswersExercise({ exercise: listItem.id, order_position: 6 });
```
and i get the same error.

I checked everything else, it is definitely the hook

I would expect the hook to delete the elements within the database independent from the fact that it may run multiple times asynchronously.

**Comment by psteinroe** [comment] 2023-12-09 14:30
hey, thanks for opening the issue!

this might sound silly, but can you try it with a "old school" `for` loop, e.g.

```ts
for (const id of conversationIds) {
  await update({ id, status });
}
```

if that doesn't work, can you check the network tab for the requests are being made? I suspect that the supabase client object is reused across calls, so that the second call has the `exercise` and `order_position` filter from both calls. I have had this once, and fixed it by using a for loop as per above to ensure that the calls are being made subsequently. The `.forEach` works a bit differently. 

Also, could you share how you setup the supabase client that you pass into  `useDeleteAnswersExercise`?

**Comment by timohuisinga** [comment] 2023-12-09 22:21
I found a solution finally after trying something different for way too long and basically waisting a lot of time xD. I basically just call them subsequently with a queue 
```ts
  // Create a queue
  const updateCacheQueue = new Array();
  // Function to process tasks in the queue
  const processQueue = async () => {
    while (updateCacheQueue.length > 0) {
      const task = updateCacheQueue.pop() as () => Promise<void>;
      await task();
    }
  };
```
```ts
    deletionArray.forEach((e) => {
      updateCacheQueue.push(() =>
        deleteAnswersExercise({
          exercise: e.exercise,
          order_position: e.order_position,
        }),
      );
    });
    processQueue();
```
I think i tried using a normal for loop, but maybe i didn't know that a simple ```await``` could make it work. The optimal behaviour would be of course that the deletionMutation works asynchronously without the need to await the previous call, but i don't know if that is even possible. 
This is the answers_exercises table. The foreign Key is the corresponding exercise in an exercises relation.

![Screenshot 2023-12-09 231935](https://github.com/psteinroe/supabase-cache-helpers/assets/65171386/e1a742e9-e452-450a-ad35-bbaf3f8500e6)

**Comment by andrejnano** [comment] 2024-01-29 15:11
I've noticed that the same issue occurs with `useUpdateMutation` (PATCH request). It appears that requests are batched together, with a filter applied simultaneously to both individual items' primary keys. I've partially and temporarily resolved this by using upserts instead of updates, which involves individual POST requests for each mutated item. However, I'm struggling to figure out how to delete more than one item at a time using the `useDeleteMutation` hook.

Additionally, I've experimented with using a global Supabase client instance as well as individual instances for each hook call, but without success so far.

**Comment by psteinroe** [comment] 2024-02-08 07:24
thanks for providing the details @timohuisinga @andrejnano. i just came back from vacation and have to sort out some other stuff first. If anyone is interested in picking it up feel free, otherwise I will do it in some time. it might be a hard nut to crack, because cache helpers just gets the supabase client passed as a prop, and then applies its own filters to it. if you call it in a loop, it will reuse the same client I suspect, leading to this error. this has to be fixed by either making sure that we use a copy of the supabase client that is passed, or by providing a new api that allows deleting and updating via array. I think the latter is cleaner.

**Comment by psteinroe** [comment] 2024-02-14 10:54
its super hard to fix this because its not reproducible via tests (see #382), just when using it in an actual app with `useSupabaseClient`. since batch updates can be fixed with batch upserts, wdyt about adding a new hook `useDeleteManyMutation` that supports delete via `supabase.from('table').delete().in('pk', [pk1, pk2])`?

Downside is that this only works if there is just a single primary key.

**Closed** 2024-02-14 14:53 UTC
Labels: bug
