### ISSUE TITLE
Question: Deleting a record's relation and invalidating a nested query

### ISSUE THREAD

**Issue by Keithcat767** [psteinroe/supabase-cache-helpers#390] opened 2024-02-27 23:55 UTC
Hello! Thank you so much for the library. It has saved me a ton of time and I really appreciate it!

This is likely a problem with my code and/or my lack of understanding, but I am a bit stumped on how to proceed. 

I have a many-to-many relationship between a table called `playgroups` and a table called `users` and therefore have a junction table called `playgroups_users`. 

My first query selects from playgroups and joins the users from the playgroup_users table:
```
  const { data: playgroup, refetch } = useQuery(
    supabaseInstance
      .from("playgroups")
      .select(
        "id, join_code, owner (id, auth_user), members:playgroup_users ( id, player (id, name, auth_user) )",
      )
      .eq("id", playgroupId)
      .single(),
  );
```

I then have a delete mutation I am using to remove a user from the playgroup. 

```  
const { mutateAsync: deleteRecord } = useDeleteMutation(
    supabaseInstance.from("playgroup_users"),
    ["id"],
  );
```

The problem is I cannot seem to invalidate the playgroups query. I have tried the `revalidateTables` and `revalidateRelations` options but neither seem to do anything. I am happy to provide how I had those configured, if it would help! But I figured I'd just pose the question of how I should be approaching this relationship. I am guessing I could query the users separately and have a new cache key just for those records - maybe that is how I should set it up? So then while I would have two API calls, the internal delete mutation logic would remove the record rather than having to perform a full refetch (how I have it currently working).

Let me know if there is anything else that would be helpful - any guidance is really appreciated!

**Comment by psteinroe** [comment] 2024-02-28 08:32
what version are you on? this is what the `revalidateRelations` option is there for. there was a bug in the swr adapter that was fixed with the latest version. could you upgrade and try again if you are not on latest?

if you are on latest, can you share a code example on how you used `revalidateRelations`?

**Comment by Keithcat767** [comment] 2024-02-28 13:34
> what version are you on? this is what the `revalidateRelations` option is there for. there was a bug in the swr adapter that was fixed with the latest version. could you upgrade and try again if you are not on latest?
> 
> if you are on latest, can you share a code example on how you used `revalidateRelations`?

I am on the latest 1.5.0. Here is the code with the `revalidateRelations`:

```
  const { mutateAsync: deleteRecord } = useDeleteMutation(
    supabaseInstance.from("playgroup_users"),
    ["id"],
    "id,playgroup",
    {
      revalidateRelations: [
        {
          relation: "playgroups",
          relationIdColumn: "id",
          fKeyColumn: "playgroup",
        },
      ],
    },
  );
```

Thanks for the help!

**Comment by Keithcat767** [comment] 2024-02-28 13:58
@psteinroe Okay, sorry, this is totally working as it is intended. I had missed that the `revalidateRelations` only marked as stale, not invalid. I have confirmed that once I perform the delete the data is refetched when the stale time is met.

For this situation, do you recommend simply calling the refetch method returned from the useQuery hook? Or is there a better way to get the data updated right after performing the delete action that I am missing?

Thanks again for the help!

**Comment by psteinroe** [comment] 2024-02-28 17:27
What adapter are you using? In swr we revalidate. In react query I am not sure since I don't use it myself. If it does not directly fetch the query this has to be fixed!

**Comment by Keithcat767** [comment] 2024-02-28 19:09
I am using React Query. I can take a look after work today and see if I can get a PR put together with a fix to fully invalidate it. I don't think it will be too tricky.

**Comment by psteinroe** [comment] 2024-02-28 20:38
Awesome! You should be able to find it easily in the cache directory. We are currently using invalidateQuery 👍🏼

**Comment by Keithcat767** [comment] 2024-02-29 00:43
Okay! I did some digging and I can see where this is failing (at least for the use case I am trying to use).

Inside the `shouldRevalidateRelation` method within core it checks if the input has the `fKeyColumn` provided in the options. In my case, the foreign key is `playgroup`, which I didn't have as a primary key and so it wasn't getting added to the input object in the `buildDeleteFetcher` method. In my case, the fKeyColumn is `playgroup` because it is from a junction table.

So, I tried adding it as a primary key, and that then makes it through to where we get the postgrest filter in delete item. 

But then in `deleteItem` when we iterate over the `cacheKeys` it then removes any primary key from not found in the filters of the queryKey we are currently on.  So in this case, because the cacheKey I want to invalidate used `id` as the primary key it only grabs that one and doesn't keep `playgroup`.

So in the end in `shouldRevalidateRelation` when it checks the input the if statement `typeof input[r.fKeyColumn] !== "undefined"` will resolve as `false` and it doesn't get invalidated. 

I hope that makes sense. I am happy to put together an example in a repo for you to take a look. It seems like maybe updating `shouldRevalidateRelation` to take in `op.input` instead of `transformedInput` for flexibility is an option. I have confirmed this works as I would expect. Although, it is also maybe a bit odd to require the foreign key column as a primary key. 

All that said, I am sure I am making some assumptions and missing some cases where these parts are needed. Let me know your thoughts!

Summary: The `playgroup` query isn't being properly invalidated because the foreign key column referencing the playgroup in my mutated object doesn't match the foreign key used in that initial query. This key then gets filtered out when `shouldRevalidateRelation` tries to check if this query is relevant to my mutation.

**Comment by psteinroe** [comment] 2024-02-29 11:55
thanks for the investigation, highly appreciated! I am still not 100% sure what the issue is to be honest. especially this part sounds like something is off 

> But then in deleteItem when we iterate over the cacheKeys it then removes any primary key from not found in the filters of the queryKey we are currently on. So in this case, because the cacheKey I want to invalidate used id as the primary key it only grabs that one and doesn't keep playgroup.

maybe we shouldn't pass `transformedInput` but `input` to the relation check?

 If you could open a pr with a failing test that would help a lot. sorry, I don't have the time to repro this myself at the moment, but happy to take a look if we can work against a test case.

**Comment by Keithcat767** [comment] 2024-02-29 15:00
Absolutely! I should be able to get one made today or tomorrow.

**Comment by Keithcat767** [comment] 2024-02-29 19:45
@psteinroe Just made a PR with a failing test and some additional comments for how it might be fixed. Let me know your thoughts! 

https://github.com/psteinroe/supabase-cache-helpers/pull/391

**Closed** 2024-02-29 21:21 UTC
