### ISSUE TITLE
React Query - Uncaught Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by butteredcorn** [psteinroe/supabase-cache-helpers#190] opened 2023-05-12 00:52 UTC
**Describe the bug**
When trying the following:

```javascript

import { useQuery } from '@supabase-cache-helpers/postgrest-react-query';
import { useSupabaseClient } from '@supabase/auth-helpers-react';

const supabase = useSupabaseClient();
  const query = useQuery(
    supabase.from('profiles').select('username, photo_url').eq('id', id).single(),
    options
  );
```

I get the error:

```javascript
Uncaught Error: No QueryClient set, use QueryClientProvider to set one
    at Object.useQueryClient (QueryClientProvider.js?a287:59:1)
    at Object.useBaseQuery (useBaseQuery.js?663d:36:1)
    at useQuery (useQuery.js?c42c:11:1)
    at useQuery (index.js?7dff:365:1)
    at useGetUser (VM115362 useGetUser.ts:16:106)
    at UserAccountPage (account.tsx?0cf5:42:45)
    at renderWithHooks (react-dom.development.js?ac89:16305:1)
    at mountIndeterminateComponent (react-dom.development.js?ac89:20074:1)
    at beginWork (react-dom.development.js?ac89:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:4213:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4277:1)
    at beginWork$1 (react-dom.development.js?ac89:27451:1)
    at performUnitOfWork (react-dom.development.js?ac89:26557:1)
    at workLoopSync (react-dom.development.js?ac89:26466:1)
    at renderRootSync (react-dom.development.js?ac89:26434:1)
    at performConcurrentWorkOnRoot (react-dom.development.js?ac89:25738:1)
    at workLoop (scheduler.development.js?c964:266:1)
    at flushWork (scheduler.development.js?c964:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js?c964:533:1)
```

I tried adding a QueryClientProvider around the SessionContext in _app.tsx, but that didn't do it. Is there an example of how to add the QueryClient somewhere?

```javascript
import { QueryCache, QueryClient, QueryClientProvider } from '@tanstack/react-query';

const queryClientRef = useRef(new QueryClient() );

      <QueryClientProvider client={queryClientRef.current}>
        <SessionContextProvider supabaseClient={supabaseClient} initialSession={initalSession}>
             {...etc}
        </SessionContextProvider>
      </QueryClientProvider>
```

**Comment by psteinroe** [comment] 2023-05-12 06:58
Hi,

thanks for reporting the issue. Unfortunately, this is not an issue with Supabase Cache Helpers. Please refer to the [React Query documentation](https://tanstack.com/query/v4/docs/react/examples/react/nextjs) for examples on how to setup the query client properly in NextJs.

**Comment by Myzel394** [comment] 2023-05-12 10:40
@butteredcorn As far as I know you don't `useRef` to store the query client but rather make it a global variable (outside of your components).

Here's how I used it in a project: https://github.com/Myzel394/kleckrelay-website/blob/master/src/App.tsx#L170
See the import at the top which uses this global variable: https://github.com/Myzel394/kleckrelay-website/blob/master/src/constants/react-query.ts#L5

**Comment by baba43** [comment] 2023-05-26 14:49
I use Next.js 13 and get the same error using `react-.query`. Using the regular `useQuery` works, but using the `useQuery` of this library, I get this error.

**Comment by psteinroe** [comment] 2023-05-26 16:42
this is most likely caused by multiple react-query version being loaded. can you check whether you have just one dependency installed? this should also be fixed by this: https://stackoverflow.com/questions/65590195/error-no-queryclient-set-use-queryclientprovider-to-set-one

**Comment by psteinroe** [comment] 2023-05-27 15:52
I will setup a react-query example, and try to reproduce this there.

**Comment by psteinroe** [comment] 2023-05-31 11:59
I can replicate. Looking to fix now 👍

**Closed** 2023-05-31 12:48 UTC
Labels: bug

**Comment by psteinroe** [comment] 2023-05-31 12:56
fixed in the latest release!
